// swift-tools-version: 6.2
import PackageDescription

// SnapActKit — photo -> category -> ranked action candidates.
//
// A package rather than files in an app target because both the app and the
// Share Extension need this code, and an extension cannot import an app
// target. Nothing here touches UIKit, so `swift test` runs the whole thing on
// the host Mac without an Xcode project.
let package = Package(
    name: "SnapActKit",
    // FoundationModels (SystemLanguageModel, @Generable) is iOS 26 / macOS 26.
    platforms: [.iOS(.v26), .macOS(.v26)],
    products: [
        .library(name: "SnapActKit", targets: ["SnapActKit"])
    ],
    targets: [
        .target(
            name: "SnapActKit"
            // Resources/actions.json is generated by tools/build_catalog.py in
            // step 2; the `.process("Resources")` rule lands with it, since
            // declaring it over an empty directory fails the build.
        ),
        .testTarget(name: "SnapActKitTests", dependencies: ["SnapActKit"]),
    ]
)
